#!/bin/sh
#
# Called by "git commit" with no parameters after a commit is made.
#
# This hook is meant primarily for notification, and cannot affect the outcome of 'git commit'.

##################################################################################
## This hook commits changes to the code branch when commiting to deploy branch. #
##################################################################################

DEPLOY_BRANCH="master"
CODE_BRANCH="code"

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "$DEPLOY_BRANCH" ]; then
	echo "Deployment branch has been commited to. Making cherry-pick of commit and committing to code branch as well"

	commit_msg="$(git log -1 --pretty=%B)"

	git stash # Stash changes not added to the commit

	git checkout "$CODE_BRANCH"

	git reset --hard

	git cherry-pick --no-commit "$DEPLOY_BRANCH"

	git reset --mixed

	# If .gitignore was changed in the other branch, the changes will be reverted
	git checkout HEAD -- .gitignore

	git add :/
	git commit -m "$commit_msg" --no-verify

	git checkout "$DEPLOY_BRANCH"

	git stash pop # Recover changes not added to the commit
fi

exit 0
