#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

##########################################################################
## This hook does multiple things:                                       #
## - Checks if the commit is being done to the code branch,              #
##   and rejects it if that is the case.                                 #
##                                                                       #
## - Checks if the package.json file exists in the build folder.         #
##   If it does not, we assume that the build failed at some point.      #
##                                                                       #
## - Checks if any changes were made to the code (or package.json)       #
##   and the build has not changed.                                      #
##                                                                       #
##   If that happens, it means that the developer forgot to run a build. #
##   Throw an error and warn them about it.                              #
##########################################################################

MAIN_BRANCH="main"
BUILD_FOLDER="build"

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "$MAIN_BRANCH" ]
then
	# If the skill build is not present, clone it
	if [ ! -d "$BUILD_FOLDER" ]
	then
		skillId=$(tr -d '\n' < ./.ask/ask-states.json | tr -d ' ' | sed -n 's/.*"profiles":{"[^{]*":{"skillId":"\(.*\)".*/\1/p' | sed 's/".*//')
		echo "$BUILD_FOLDER" | ask init --hosted-skill-id "$skillId"
	fi

	npm run build

	commit_msg="$(git log -1 --pretty=%B)"

	git --git-dir="$BUILD_FOLDER/.git" --work-tree="$BUILD_FOLDER" commit -am "$commit_msg"
fi
