#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

############################################################################
## This hook does the following:                                           #
##                                                                         #
## Checks if the commit is being done to the main branch.                  #
## If it is, it creates a build and commits the changes to the Alexa repo. #
##                                                                         #
## Note: If the Alexa repo is not present locally, it is cloned.           #
############################################################################

MAIN_BRANCH="main"
BUILD_FOLDER="build"

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "$MAIN_BRANCH" ]
then
	# If the skill build is not present, clone it
	if [ ! -d "$BUILD_FOLDER" ]
	then
		skillId=$(tr -d '\n' < ./.ask/ask-states.json | tr -d ' ' | sed -n 's/.*"profiles":{"[^{]*":{"skillId":"\(.*\)".*/\1/p' | sed 's/".*//')
		echo "$BUILD_FOLDER" | ask init --hosted-skill-id "$skillId"
	fi

	npm run build

	commit_msg="$(git log -1 --pretty=%B)"

	git --git-dir="$BUILD_FOLDER/.git" --work-tree="$BUILD_FOLDER" commit -am "$commit_msg"
fi
