#!/bin/bash

################################################################################
# This hook is called by "git push" after it has checked the remote status,    #
# but before anything has been pushed.                                         #
# If this script exits with a non-zero status nothing will be pushed.          #
#                                                                              #
# This hook is called with the following parameters:                           #
#                                                                              #
# $1 -- Name of the remote to which the push is being done                     #
# $2 -- URL to which the push is being done                                    #
#                                                                              #
# If pushing without using a named remote those arguments will be equal.       #
#                                                                              #
# Information about the commits which are being pushed is supplied as lines to #
# the standard input in the form:                                              #
#                                                                              #
#   <local ref> <local sha1> <remote ref> <remote sha1>                        #
################################################################################

MAIN_BRANCH="main"

DEPLOY_MAIN_BRANCH="master"
DEPLOY_DEV_BRANCH="dev"

BUILD_FOLDER="build"

while read local_ref local_sha remote_ref remote_sha
do
	echo "Pushing branch: $local_ref"
	if [ "$local_ref" = "refs/heads/$MAIN_BRANCH" ]
	then
		echo "Main branch is being pushed. Deploying changes to Alexa."

		cd "$BUILD_FOLDER"

		# Deploy: Pushing main branch
		git switch $DEPLOY_MAIN_BRANCH
		git push
		
		# D Merging main branch into dev branch and pushing it
		git switch $DEPLOY_DEV_BRANCH
		git merge $DEPLOY_MAIN_BRANCH
		git push --no-verify
		git switch $DEPLOY_MAIN_BRANCH
	fi
done

exit 0
